crm/urls.py
from django.urls import path
from .views import (
    admin_dashboard_view, 
    educ_media_upload_view,
    lc_media_upload_view,
    other_media_upload_view,
    UserPartnerCreateView,
    UserPartnerListView,
    UserPartnerUpdateView,
    UserPartnerResumeCreateView,
    UserPartnerResumeUpdateView,
    UserPartnerWithResumeListView,
    UserPartnerMediaUpload,
)

app_name = 'crm'

urlpatterns = [

    # Dashboard
    path('admin/dashboard/', admin_dashboard_view, name='admin_dashboard_view'),

    path('educ_media_upload/', educ_media_upload_view, name='educ_media_upload'),
    path('lc_media_upload/', lc_media_upload_view, name='lc_media_upload'),
    path('other_media_upload/', other_media_upload_view, name='other_media_upload'),

    path('admin/partner_create/', UserPartnerCreateView.as_view(), name='admin_partner_create_view'),
    path('admin/partner_update/<slug:pk>/', UserPartnerUpdateView.as_view(), name='admin_partner_update_view'),
    path('admin/partner_list/', UserPartnerListView.as_view(), name='admin_partner_list_view'),
    path('admin/partner_resume_create/<slug:pk>/', UserPartnerResumeCreateView.as_view(), name='admin_partner_resume_create_view'),
    path('admin/partner_resume_update/<slug:pk>/', UserPartnerResumeUpdateView.as_view(), name='admin_partner_resume_update_view'),
    path('admin/partner_with_resume_list/', UserPartnerWithResumeListView.as_view(), name='admin_partner_with_resume_list_view'),
    path('admin/partner_media_upload/<slug:pk>/', UserPartnerMediaUpload.as_view(), name='admin_partner_media_upload_view'),

]

partners/urls.py
from django.urls import path

from .views import (
    educ_media_upload_view,
    lc_media_upload_view,
    other_media_upload_view,

    PartnerDashboardView,
    PartnerUpdateView,
    PartnerResumePanelView,
    PartnerEducationView,
    PartnerLicensesView,
    PartnerCertificationsView,
    PartnerReferencesView,
    PartnerSkillsView,
    PartnerWorkExperiencesView,
    PartnerProfessionalSummaryView,
    PartnerCoverLetterView,
    PartnerMediaUpload,

    PartnerEducationUpdateView,
    PartnerLicensesUpdateView,
    PartnerCertificationsUpdateView,
    PartnerReferencesUpdateView,
)

app_name = 'partners'

urlpatterns = [

    # Dashboard
    path('dashboard/', PartnerDashboardView.as_view(), name='partner_dashboard_view'),

    # Media upload functions
    path('educ_media_upload/', educ_media_upload_view, name='educ_media_upload'),
    path('lc_media_upload/', lc_media_upload_view, name='lc_media_upload'),
    path('other_media_upload/', other_media_upload_view, name='other_media_upload'),

    # Update partner
    path('account/update/', PartnerUpdateView.as_view(), name='partner_account_update_view'),

    # Resume panel
    path('resume-panel/', PartnerResumePanelView.as_view(), name='partner_resume_panel_view'),

    path('my-education/', PartnerEducationView.as_view(), name='partner_education_view'),
    path('my-licenses/', PartnerLicensesView.as_view(), name='partner_licenses_view'),
    path('my-certifications/', PartnerCertificationsView.as_view(), name='partner_certifications_view'),
    path('my-references/', PartnerReferencesView.as_view(), name='partner_references_view'),
    path('my-skills/', PartnerSkillsView.as_view(), name='partner_skills_view'),
    path('my-work-experiences/', PartnerWorkExperiencesView.as_view(), name='partner_work_experiences_view'),
    path('my-professional-summary/', PartnerProfessionalSummaryView.as_view(), name='partner_professional_summary_view'),
    path('my-cover-letter/', PartnerCoverLetterView.as_view(), name='partner_cover_letter_view'),
    path('my-documents/', PartnerMediaUpload.as_view(), name='partner_media_upload_view'),

    path('my-education/update/', PartnerEducationUpdateView.as_view(), name='partner_education_update_view'),
    path('my-licenses/update/', PartnerLicensesUpdateView.as_view(), name='partner_licenses_update_view'),
    path('my-certifications/update/', PartnerCertificationsUpdateView.as_view(), name='partner_certifications_update_view'),
    path('my-references/update/', PartnerReferencesUpdateView.as_view(), name='partner_references_update_view'),


]

partners/models.py
from datetime import date, timezone

from django.db import models
from profiles.models import PartnerUser

class PartnerEducation(models.Model):
    DEGREE_TYPES = (
        (1, 'Highschool'),
        (2, 'Associate'),
        (3, 'Bachelor'),
        (4, 'Master'),
        (5, 'Doctorate'),
        (6, 'Unspecified'),
    )

    degree_type=models.IntegerField(choices=DEGREE_TYPES, default=1)
    school_name=models.CharField(max_length=255, blank=True, null=True)
    field_name=models.CharField(max_length=255, blank=True, null=True)
    date_graduated=models.CharField(max_length=255, blank=True, null=True)
    school_address=models.CharField(max_length=255, blank=True, null=True)
    file=models.FileField(upload_to='partners', blank=True, null=True)
    is_added_by_admin=models.BooleanField(default=False)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    auth_user_id=models.ForeignKey(PartnerUser, related_name='partnereducations', on_delete=models.CASCADE)

    def __str__(self):
        return self.school_name

    def get_days_ago(self):
        return ((date.today() - self.created.date()).days)


class PartnerEducationMedia(models.Model):
    MEDIA_TYPE_CHOICES=((1,"Image"),)
    MEDIA_FORMAT_CHOICES=((1, "JPG"), (2, "PNG"), (3, "PDF"))
    media_filename=models.CharField(max_length=255, default='no name')
    media_type=models.IntegerField(choices=MEDIA_TYPE_CHOICES, default=1)
    media_format=models.IntegerField(choices=MEDIA_FORMAT_CHOICES, default=1)
    media_content=models.FileField(upload_to='education_files', blank=True)
    is_active=models.IntegerField(default=1)
    is_added_by_admin=models.BooleanField(default=False)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    auth_user_id=models.ForeignKey(PartnerUser, related_name='partnereducationmedias', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.media_filename}"

    def get_date_only(self):
        return f"five"


class PartnerLCMedia(models.Model):
    MEDIA_TYPE_CHOICES=((1,"Image"),)
    MEDIA_FORMAT_CHOICES=((1, "JPG"), (2, "PNG"), (3, "PDF"))
    media_filename=models.CharField(max_length=255, default='no name')
    media_type=models.IntegerField(choices=MEDIA_TYPE_CHOICES, default=1)
    media_format=models.IntegerField(choices=MEDIA_FORMAT_CHOICES, default=1)
    media_content=models.FileField(upload_to='lc_files', blank=True)
    is_active=models.IntegerField(default=1)
    is_added_by_admin=models.BooleanField(default=False)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    auth_user_id=models.ForeignKey(PartnerUser, related_name='partnerlcmedias', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.media_filename}"


class PartnerOtherMedia(models.Model):
    MEDIA_TYPE_CHOICES=((1,"Image"),)
    MEDIA_FORMAT_CHOICES=((1, "JPG"), (2, "PNG"), (3, "PDF"))
    media_filename=models.CharField(max_length=255, default='no name')
    media_type=models.IntegerField(choices=MEDIA_TYPE_CHOICES, default=1)
    media_format=models.IntegerField(choices=MEDIA_FORMAT_CHOICES, default=1)
    media_content=models.FileField(upload_to='other_files', blank=True)
    is_active=models.IntegerField(default=1)
    is_added_by_admin=models.BooleanField(default=False)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    auth_user_id=models.ForeignKey(PartnerUser, related_name='partnerothermedias', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.media_filename}"


class PartnerLicense(models.Model):
    license_name=models.CharField(max_length=255, blank=True, null=True)
    license_code=models.CharField(max_length=255, blank=True, null=True)
    expiration_date=models.CharField(max_length=255, blank=True, null=True)
    address_acquired=models.CharField(max_length=255, blank=True, null=True)
    file=models.FileField(upload_to='partners', blank=True, null=True)
    is_compact = models.CharField(max_length=10, blank=True, null=True)
    is_added_by_admin=models.BooleanField(default=False)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    auth_user_id=models.ForeignKey(PartnerUser, related_name='partnerlicenses', on_delete=models.CASCADE)

    def __str__(self):
        return self.license_name

    def get_days_ago(self):
        return ((date.today() - self.created.date()).days)


class PartnerCertification(models.Model):
    cert_name=models.CharField(max_length=255, blank=True, null=True)
    cert_code=models.CharField(max_length=255, blank=True, null=True)
    expiration_date=models.CharField(max_length=255, blank=True, null=True)
    address_acquired=models.CharField(max_length=255, blank=True, null=True)
    file=models.FileField(upload_to='partners', blank=True, null=True)
    is_added_by_admin=models.BooleanField(default=False)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    auth_user_id=models.ForeignKey(PartnerUser, related_name='partnercertifications', on_delete=models.CASCADE)

    def __str__(self):
        return self.cert_name

    def get_days_ago(self):
        return ((date.today() - self.created.date()).days)

class PartnerReference(models.Model):
    name=models.CharField(max_length=255, blank=True, null=True)
    position=models.CharField(max_length=255, blank=True, null=True)
    phone_number=models.CharField(max_length=255, blank=True, null=True)
    email=models.CharField(max_length=255, blank=True, null=True)
    office_name=models.CharField(max_length=255, blank=True, null=True)
    office_address=models.CharField(max_length=255, blank=True, null=True)
    file=models.FileField(upload_to='partners', blank=True, null=True)
    start_date=models.CharField(max_length=255, blank=True, null=True)
    end_date=models.CharField(max_length=255, blank=True, null=True)
    is_added_by_admin=models.BooleanField(default=False)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    auth_user_id=models.ForeignKey(PartnerUser, related_name='partnerreferences', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_days_ago(self):
        return ((date.today() - self.created.date()).days)


class PartnerSkill(models.Model):
    skill_name=models.CharField(max_length=255, null=True, blank=True)
    is_added_by_admin=models.BooleanField(default=False)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    auth_user_id=models.ForeignKey(PartnerUser, related_name='partnerskills', on_delete=models.CASCADE)

    def __str__(self):
        return self.skill_name

    def get_days_ago(self):
        return ((date.today() - self.created.date()).days)


class PartnerCoverLetter(models.Model):
    letter=models.TextField(default='')
    is_added_by_admin=models.BooleanField(default=False)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    auth_user_id=models.ForeignKey(PartnerUser, related_name='partnercoverletters', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.created}"

    def get_days_ago(self):
        return ((date.today() - self.created.date()).days)


class PartnerProfessionalSummary(models.Model):
    summary=models.TextField(default='')
    is_added_by_admin=models.BooleanField(default=False)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    auth_user_id=models.ForeignKey(PartnerUser, related_name='partnerprofessionalsummaries', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.created}"

    def get_days_ago(self):
        return ((date.today() - self.created.date()).days)


class PartnerWorkHistory(models.Model):
    designation=models.CharField(max_length=255, blank=True, null=True)
    phone_number=models.CharField(max_length=255, blank=True, null=True)
    email=models.CharField(max_length=255, blank=True, null=True)
    office_name=models.CharField(max_length=255, blank=True, null=True)
    office_address=models.CharField(max_length=255, blank=True, null=True)
    start_date=models.CharField(max_length=255, blank=True, null=True)
    end_date=models.CharField(max_length=255, blank=True, null=True)
    responsibilities=models.TextField(default='')
    is_added_by_admin=models.BooleanField(default=False)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    auth_user_id=models.ForeignKey(PartnerUser, related_name='partnerworkhistories', on_delete=models.CASCADE)

    def __str__(self):
        return self.designation

    def get_days_ago(self):
        return ((date.today() - self.created.date()).days)


class PartnerResponsibility(models.Model):
    position=models.CharField(max_length=255, blank=True, null=True)
    work_history_id=models.ForeignKey(PartnerWorkHistory, related_name='partnerresponsibilities', on_delete=models.CASCADE)

    def __str__(self):
        return self.position

    def get_days_ago(self):
        return ((date.today() - self.created.date()).days)

partners/templates/partners/partner_certifications.html
{% extends "partners/base.html" %}

{% load static %}

{% block custom_css %}
<style>
hr {
  margin-top: 2rem;
  margin-bottom: 1rem;
  width: 50%;
  border: 0;
  border-top: 1px solid rgba(0, 0, 0, 0.1);
}
</style>
{% endblock custom_css %}

{% block title %}
    My Certifications
{% endblock title %}


{% block page_title %}
    My Certifications
{% endblock page_title %}

{% block page_content %}
    <form id="certificationsForm">
    {% csrf_token %}
    <div class="row">
        <div class="col-12">
            <div class="row mt-4">
                <div class="col-12 col-lg-6 offset-lg-3">
                    <div class="card">
                        <div class="card-body">
                            <p class="lead">Add Certifications</p>
                            
                            <!-- Certifications -------------------------------->
                            <div class="certifications_div">

                                <div class="row certifications_div_row first_certifications">


                                    <div class="col-lg-12">
                                        <div class="form-group mb-2">
                                            <label class="col-lg-12 mb-1">Name</label>
                                            <div class="col-lg-12 mt-0">
                                                <input type="text" name="certification_name[]" class="form-control certification_name">
                                            </div>
                                        </div>

                                        <div class="form-group mb-2">
                                            <label class="col-lg-12 mb-1">Code</label>
                                            <div class="col-lg-12 mt-0">
                                                <input type="text" name="certification_code[]" class="form-control certification_code">
                                            </div>
                                        </div>

                                        <div class="form-group mb-2">
                                            <label class="col-lg-12 mb-1">Expiration Date</label>
                                            <div class="col-lg-12 mt-0">
                                                <input type="text" name="certification_expiration_date[]" class="form-control certification_expiration_date" placeholder="YYYY-MM-DD">
                                            </div>
                                        </div>
                                        
                                        <div class="form-group mb-2">
                                            <label class="col-lg-12 mb-1">Address</label>
                                            <div class="col-lg-12 mt-0">
                                                <input  type="text" class="form-control certification_address" name="certification_address[]">
                                            </div>
                                        </div>

                                    </div>

                                    <hr/>

                                </div>
                            </div>

                            

                            <div class="btn float-right mt-4">

                                <a href="#remove_certifications" class="btn btn-warning remove_certifications" id="remove_certifications">Remove</a>
                                <a href="#add_certifications" class="btn btn-primary add_certifications" id="add_certifications">Add More</a>

                            </div>

                            <!-- endCertifications -------------------------------->

                        </div>
                    </div>

                    <div class="card mt-4">
                        <div class="card-body">

                            <div class="row mb-5">
                                <div class="col-lg-12">
                                    <div class='progress mb-3' style="height:auto">
                                        <div class="progress-bar bg-warning" id="progressbar" role="progressbar" data-width="0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="display:none;width: 0%;height: 15px;border-radius: 15px;">0%</div>
                                    </div>
                                </div>
                            </div>

                            <button type="button" class="btn btn-primary btn-block submit_btn mt-5">SAVE CERTIFICATIONS</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </form>
{% endblock page_content %}

{% block custom_js %}

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="{% static 'partners/modules/sweetalert/sweetalert.min.js' %}"></script>
<script src="{% static 'partners/js/page/modules-sweetalert.js' %}"></script>

<script>
    
    /*
        Add certifications button
        Remove certifications button
    */
    $(".add_certifications").click(function(){
        
        if($(".certifications_div").find(".certifications_div_row").length < 3){
            var certifications_row = $(".first_certifications").clone();
            certifications_row.removeClass("first_certifications");
            certifications_row.find(".certification_name").val("");
            certifications_row.find(".certification_code").val("");
            certifications_row.find(".certification_expiration_date").val("");
            certifications_row.find(".certification_address").val("");
            $(".certifications_div").append(certifications_row);
        }
    });

    $(".remove_certifications").click(function(){
        if($(".certifications_div").find(".certifications_div_row").length > 1){
            $(".certifications_div").children().last().remove();
        }
        else{

        }
    });

    /*
        Ajax request
        Sending data to server
    */
    $(".submit_btn").click(function(){

        var form = new FormData($("#certificationsForm")[0]);
        
        var xhr = new XMLHttpRequest();
        xhr.onreadystatechange = function() {
            if (xhr.status == 200){
                console.log(xhr.responseText);
            }
        }
        xhr.open("POST","{% url 'partners:partner_certifications_view' %}", true);

        $("#progressbar").show();

        xhr.upload.addEventListener("progress", function(ev) {
            if(ev.lengthComputable) {
                var percentage = (ev.loaded/ev.total*100|0);
                $("#progressbar").css({"width":""+percentage+"%"}).text("Uploaded .."+percentage+"%");
                setTimeout(function(){
                    $(document).ready(function() {
                        swal('Success', 'You just added certifications!', 'success').then(function() {
                            window.location.href = "{% url 'partners:partner_resume_panel_view' %}";
                    })});
                }, 1000);
                
            }
            
        });

        xhr.send(form);
        
    })

</script>

{% endblock custom_js %}

partners/templates/partners/partner_cover_letter.html
{% extends "partners/base.html" %}

{% load static %}

{% block custom_css %}
<style>
hr {
  margin-top: 2rem;
  margin-bottom: 1rem;
  width: 50%;
  border: 0;
  border-top: 1px solid rgba(0, 0, 0, 0.1);
}
</style>
{% endblock custom_css %}

{% block title %}
    My Cover Letter
{% endblock title %}


{% block page_title %}
    My Cover Letter
{% endblock page_title %}

{% block page_content %}

    <form id="coverletterForm">
    {% csrf_token %}
        <div class="row">
            <div class="col-12 col-md-6 col-sm-12">
            </div>
            <div class="col-12 col-md-6 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <p class="lead">Compose Cover Letter</p>
                        
                        <div class="col-lg-12">
                            <textarea class="form-control" name="cover_letter" id="cover_letter">{% if partner_cover_letter %}{{ partner_cover_letter.letter }}{% endif %}</textarea>
                        </div>

                    </div>
                </div>

                <div class="card mt-4">
                    <div class="card-body">

                        <div class="row mb-5">
                            <div class="col-lg-12">
                                <div class='progress mb-3' style="height:auto">
                                    <div class="progress-bar bg-warning" id="progressbar" role="progressbar" data-width="0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="display:none;width: 0%;height: 15px;border-radius: 15px;">0%</div>
                                </div>
                            </div>
                        </div>

                        <button type="button" class="btn btn-primary btn-block submit_btn mt-5">SAVE COVER LETTER</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock page_content %}

{% block custom_js %}
<script src="//cdn.tiny.cloud/1/f2rkbc3dctxrbtvg56h17qkspz197y3fd9q28dnwt2frj6gj/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="{% static 'partners/modules/sweetalert/sweetalert.min.js' %}"></script>
<script src="{% static 'partners/js/page/modules-sweetalert.js' %}"></script>

<script>
    tinymce.init({
        selector: "textarea#cover_letter",
        height: 700,
        menubar: false,
        plugins: [
            "lists",
        ],
        toolbar: "insertfile undo redo | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent",
        force_br_newlines : true,
        force_p_newlines : false,
    });
</script>

<script>
    
    
    /*
        Ajax request
        Sending data to server
    */
    $(".submit_btn").click(function(){

        var form = new FormData($("#coverletterForm")[0]);

        var content = tinyMCE.editors[0].getContent();

        form.append("cover_letter", content);
        
        var xhr = new XMLHttpRequest();
        xhr.onreadystatechange = function() {
            if (xhr.status == 200){
                console.log(xhr.responseText);
            }
        }
        xhr.open("POST","{% url 'partners:partner_cover_letter_view' %}", true);

        $("#progressbar").show();

        xhr.upload.addEventListener("progress", function(ev) {
            if(ev.lengthComputable) {
                var percentage = (ev.loaded/ev.total*100|0);
                $("#progressbar").css({"width":""+percentage+"%"}).text("Uploaded .."+percentage+"%");
                setTimeout(function(){
                    $(document).ready(function() {
                        swal('Success', 'You just added your professional summary!', 'success').then(function() {
                            window.location.href = "{% url 'partners:partner_resume_panel_view' %}";
                    })});
                }, 1000);
                
            }
            
        });

        xhr.send(form);
        
    })

</script>

{% endblock custom_js %}

partners/templates/partners/partner_dashboard.html
{% extends "partners/base.html" %}

{% block title %}
    Care Partners Dashboard
{% endblock title %}


{% block page_title %}
    Care Partners Dashboard
{% endblock page_title %}

{% block page_content %}
    
    <div class="row">
        <div class="col-12 mb-4">
            <div class="hero bg-primary text-white">
                <div class="hero-inner">
                <h2>Welcome, {{ partner_user.auth_user_id.first_name }}</h2>
                <p class="lead">You're almost done, please fill in some information about your account to complete the registration.</p>
                <div class="mt-4">
                    <a href="{% url 'partners:partner_account_update_view' %}" class="btn btn-outline-white btn-lg btn-icon icon-left"><i class="far fa-user"></i> Complete Account Setup </a>
                </div>
                </div>
            </div>
        </div>
    </div>

    <div class="section-body">
        <h2 class="section-title">Start earning your first paycheck!</h2>
        <p class="section-lead">These are the next simple steps to become a full-pledged Care Partner.</p>

        <div class="row">
            <div class="col-12 col-md-6 col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Setup Resume</h4>
                    </div>
                    <div class="card-body">
                        <div class="empty-state" data-height="400" style="height: 400px;">
                            <div class="empty-state-icon bg-primary">
                                <i class="fas fa-question"></i>
                            </div>
                            <h2>Boost Your Online Presence</h2>
                            <p class="lead">
                                Showcase your work experiences, education, skills, and qualifications in a standardized format.
                            </p>
                            <a href="{% url 'partners:partner_resume_panel_view' %}" class="btn btn-primary mt-4">Setup My Resume</a>
                            <a href="#" class="mt-4 bb">Need Help?</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-6 col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Pre-Screening Process</h4>
                    </div>
                    <div class="card-body">
                        <div class="empty-state" data-height="400" style="height: 400px;">
                            <div class="empty-state-icon bg-danger">
                                <i class="fas fa-user-check"></i>
                            </div>
                            <h2>Background Brief Review</h2>
                            <p class="lead">
                                One of our staff will conduct a unique pre-screening call for verification.
                            </p>
                            <a href="#" class="btn btn-warning mt-4">Set A Schedule</a>
                            <a href="#" class="mt-4 bb">Find Hints</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>   
   

{% endblock page_content %}