crm/urls.py
from django.urls import path
from .views import (
    admin_dashboard_view, 
    educ_media_upload_view,
    lc_media_upload_view,
    other_media_upload_view,
    UserPartnerCreateView,
    UserPartnerListView,
    UserPartnerUpdateView,
    UserPartnerResumeCreateView,
    UserPartnerResumeUpdateView,
    UserPartnerWithResumeListView,
    UserPartnerMediaUpload,
)

app_name = 'crm'

urlpatterns = [

    # Dashboard
    path('admin/dashboard/', admin_dashboard_view, name='admin_dashboard_view'),

    path('educ_media_upload/', educ_media_upload_view, name='educ_media_upload'),
    path('lc_media_upload/', lc_media_upload_view, name='lc_media_upload'),
    path('other_media_upload/', other_media_upload_view, name='other_media_upload'),

    path('admin/partner_create/', UserPartnerCreateView.as_view(), name='admin_partner_create_view'),
    path('admin/partner_update/<slug:pk>/', UserPartnerUpdateView.as_view(), name='admin_partner_update_view'),
    path('admin/partner_list/', UserPartnerListView.as_view(), name='admin_partner_list_view'),
    path('admin/partner_resume_create/<slug:pk>/', UserPartnerResumeCreateView.as_view(), name='admin_partner_resume_create_view'),
    path('admin/partner_resume_update/<slug:pk>/', UserPartnerResumeUpdateView.as_view(), name='admin_partner_resume_update_view'),
    path('admin/partner_with_resume_list/', UserPartnerWithResumeListView.as_view(), name='admin_partner_with_resume_list_view'),
    path('admin/partner_media_upload/<slug:pk>/', UserPartnerMediaUpload.as_view(), name='admin_partner_media_upload_view'),

]

profiles/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    USER_TYPE_CHOICES=((1, "Admin"), (2, "Staff"), (3, "Partner"), (4, "Patient"))
    user_type=models.IntegerField(choices=USER_TYPE_CHOICES, default=1)


class AdminUser(models.Model):
    profile_pic=models.ImageField(upload_to='avatars', default='no_photo.png')
    auth_user_id=models.OneToOneField(CustomUser, related_name='adminusers', on_delete=models.CASCADE)
    bio=models.TextField(default="no bio...")
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Admin: {self.auth_user_id}"


class StaffUser(models.Model):
    profile_pic=models.ImageField(upload_to='avatars', default='no_photo.png')
    auth_user_id=models.OneToOneField(CustomUser, related_name='staffusers', on_delete=models.CASCADE)
    bio=models.TextField(default="no bio...")
    is_added_by_admin=models.BooleanField(default=False)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Staff: {self.auth_user_id}"


class PartnerUser(models.Model):
    profile_pic=models.ImageField(upload_to='avatars', default='no_photo.png')
    auth_user_id=models.OneToOneField(CustomUser, related_name='partnerusers', on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    address_line_1=models.CharField(max_length=255, null=True, blank=True)
    address_line_2=models.CharField(max_length=255, null=True, blank=True)
    address_town=models.CharField(max_length=120, null=True, blank=True)
    address_region=models.CharField(max_length=120, null=True, blank=True)
    address_country=models.CharField(max_length=120, null=True, blank=True)
    address_zip_code=models.CharField(max_length=20, null=True, blank=True)
    progress_mark=models.IntegerField(default=20)
    is_added_by_admin=models.BooleanField(default=False)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Partner: {self.auth_user_id}"


class PatientUser(models.Model):
    profile_pic=models.ImageField(upload_to='avatars', default='no_photo.png')
    auth_user_id=models.OneToOneField(CustomUser, related_name='patientusers', on_delete=models.CASCADE)
    date_of_birth = models.DateTimeField(blank=True, null=True)
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    address_line_1=models.CharField(max_length=255, null=True, blank=True)
    address_line_2=models.CharField(max_length=255, null=True, blank=True)
    address_town=models.CharField(max_length=120, null=True, blank=True)
    address_region=models.CharField(max_length=120, null=True, blank=True)
    address_country=models.CharField(max_length=120, null=True, blank=True)
    address_zip_code=models.CharField(max_length=20, null=True, blank=True)
    is_added_by_admin=models.BooleanField(default=False)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Patient: {self.auth_user_id}"

crm/views.py
import os

from datetime import date

from django.contrib.messages.views import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.core.serializers import serialize
from django.db.models import Q, fields
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import CreateView, DeleteView, ListView, UpdateView, View

from profiles.models import CustomUser, PartnerUser

from partners.models import (
    PartnerEducation,
    PartnerLicense,
    PartnerCertification,
    PartnerReference,
    PartnerSkill,
    PartnerCoverLetter,
    PartnerEducationMedia,
    PartnerLCMedia,
    PartnerOtherMedia, 
    PartnerProfessionalSummary,
    PartnerWorkHistory,
)

def admin_dashboard_view(request):
    return render(request, 'crm/admin_dashboard.html')

def educ_media_upload_view(request):
    if request.method == 'POST':
        media_file_name = request.FILES.get('file').name
        media_file = request.FILES.get('file')

        # TODO: hash the file size for extra validation in duplication
        file_format = ''

        if media_file_name.endswith('.jpg') or media_file_name.endswith('.jpeg'):
            file_format = 1
        if media_file_name.endswith('.png'):
            file_format = 2
        if media_file_name.endswith('.pdf'):
            file_format = 3
        
        partner_id = request.POST.get('partner_id')
        partner_instance = PartnerUser.objects.get(id=partner_id)
        obj, created = PartnerEducationMedia.objects.get_or_create(auth_user_id=partner_instance, media_filename=media_file_name, media_format=file_format)

        if created:
            obj.media_content = media_file
            obj.save()

            qs_ed = PartnerEducationMedia.objects.filter(auth_user_id=partner_instance)
            qs_lc = PartnerLCMedia.objects.filter(auth_user_id=partner_instance)
            qs_od = PartnerOtherMedia.objects.filter(auth_user_id=partner_instance)
            data_ed = serialize("json", qs_ed, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))
            data_lc = serialize("json", qs_lc, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))
            data_od = serialize("json", qs_od, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))

            return JsonResponse({'ex': False, 'data_ed': data_ed, 'data_lc': data_lc, 'data_od': data_od})
        
        else:

            qs_ed = PartnerEducationMedia.objects.filter(auth_user_id=partner_instance)
            qs_lc = PartnerLCMedia.objects.filter(auth_user_id=partner_instance)
            qs_od = PartnerOtherMedia.objects.filter(auth_user_id=partner_instance)
            data_ed = serialize("json", qs_ed, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))
            data_lc = serialize("json", qs_lc, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))
            data_od = serialize("json", qs_od, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))

            return JsonResponse({'ex': True, 'data_ed': data_ed, 'data_lc': data_lc, 'data_od': data_od})

    return HttpResponse()


def lc_media_upload_view(request):
    if request.method == 'POST':
        media_file_name = request.FILES.get('file').name
        media_file = request.FILES.get('file')

        # TODO: hash the file size for extra validation in duplication
        file_format = ''

        if media_file_name.endswith('.jpg') or media_file_name.endswith('.jpeg'):
            file_format = 1
        if media_file_name.endswith('.png'):
            file_format = 2
        if media_file_name.endswith('.pdf'):
            file_format = 3
        
        partner_id = request.POST.get('partner_id')
        partner_instance = PartnerUser.objects.get(id=partner_id)
        obj, created = PartnerLCMedia.objects.get_or_create(auth_user_id=partner_instance, media_filename=media_file_name, media_format=file_format)

        if created:
            obj.media_content = media_file
            obj.save()

            qs_ed = PartnerEducationMedia.objects.filter(auth_user_id=partner_instance)
            qs_lc = PartnerLCMedia.objects.filter(auth_user_id=partner_instance)
            qs_od = PartnerOtherMedia.objects.filter(auth_user_id=partner_instance)
            data_ed = serialize("json", qs_ed, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))
            data_lc = serialize("json", qs_lc, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))
            data_od = serialize("json", qs_od, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))

            return JsonResponse({'ex': False, 'data_ed': data_ed, 'data_lc': data_lc, 'data_od': data_od})
        
        else:

            qs_ed = PartnerEducationMedia.objects.filter(auth_user_id=partner_instance)
            qs_lc = PartnerLCMedia.objects.filter(auth_user_id=partner_instance)
            qs_od = PartnerOtherMedia.objects.filter(auth_user_id=partner_instance)
            data_ed = serialize("json", qs_ed, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))
            data_lc = serialize("json", qs_lc, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))
            data_od = serialize("json", qs_od, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))

            return JsonResponse({'ex': True, 'data_ed': data_ed, 'data_lc': data_lc, 'data_od': data_od})

    return HttpResponse()

def other_media_upload_view(request):
    if request.method == 'POST':
        media_file_name = request.FILES.get('file').name
        media_file = request.FILES.get('file')

        # TODO: hash the file size for extra validation in duplication
        file_format = ''

        if media_file_name.endswith('.jpg') or media_file_name.endswith('.jpeg'):
            file_format = 1
        if media_file_name.endswith('.png'):
            file_format = 2
        if media_file_name.endswith('.pdf'):
            file_format = 3
        
        partner_id = request.POST.get('partner_id')
        partner_instance = PartnerUser.objects.get(id=partner_id)
        obj, created = PartnerOtherMedia.objects.get_or_create(auth_user_id=partner_instance, media_filename=media_file_name, media_format=file_format)

        if created:
            obj.media_content = media_file
            obj.save()

            qs_ed = PartnerEducationMedia.objects.filter(auth_user_id=partner_instance)
            qs_lc = PartnerLCMedia.objects.filter(auth_user_id=partner_instance)
            qs_od = PartnerOtherMedia.objects.filter(auth_user_id=partner_instance)
            data_ed = serialize("json", qs_ed, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))
            data_lc = serialize("json", qs_lc, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))
            data_od = serialize("json", qs_od, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))

            return JsonResponse({'ex': False, 'data_ed': data_ed, 'data_lc': data_lc, 'data_od': data_od})
        
        else:

            qs_ed = PartnerEducationMedia.objects.filter(auth_user_id=partner_instance)
            qs_lc = PartnerLCMedia.objects.filter(auth_user_id=partner_instance)
            qs_od = PartnerOtherMedia.objects.filter(auth_user_id=partner_instance)
            data_ed = serialize("json", qs_ed, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))
            data_lc = serialize("json", qs_lc, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))
            data_od = serialize("json", qs_od, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))

            return JsonResponse({'ex': True, 'data_ed': data_ed, 'data_lc': data_lc, 'data_od': data_od})

    return HttpResponse()


class UserPartnerCreateView(SuccessMessageMixin, CreateView):

    model = CustomUser
    template_name = 'crm/admin_partner_create.html'
    success_message = 'Partner added successfully!'
    fields = (
        'first_name',
        'last_name',
        'email',
        'username',
        'password',
    )

    def form_valid(self, form):

        user = form.save(commit=False)
        user.is_active = True
        user.user_type = 3
        user.set_password(form.cleaned_data['password'])
        user.save()

        # Saving user.partnerusers
        user.partnerusers.profile_pic = self.request.FILES['profile_pic']
        user.partnerusers.date_of_birth = date(*map(int, self.request.POST.get('date_of_birth').split('-')))
     
        user.partnerusers.phone_number = self.request.POST.get('phone_number')
        user.partnerusers.address_line_1 = self.request.POST.get('address_line_1')
        user.partnerusers.address_line_2 = self.request.POST.get('address_line_2')
        user.partnerusers.address_town = self.request.POST.get('address_town')
        user.partnerusers.address_region = self.request.POST.get('address_region')
        user.partnerusers.address_country = self.request.POST.get('address_country')
        user.partnerusers.address_zip_code = self.request.POST.get('address_zip_code')

        is_added_by_admin = False

        if self.request.POST.get('is_added_by_admin') == 'on':
            is_added_by_admin = True

        user.partnerusers.is_added_by_admin = is_added_by_admin
        user.save()

        messages.success(self.request, 'Partner user created')

        return HttpResponseRedirect(reverse('crm:admin_partner_list_view'))


class UserPartnerUpdateView(SuccessMessageMixin, UpdateView):

    model = CustomUser
    template_name = 'crm/admin_partner_update.html'

crm/templates/crm/admin_dashboard.html
{% extends "crm/base.html" %}

{% block title %}
    Dashboard
{% endblock title %}


{% block page_title %}
    Dashboard
{% endblock page_title %}

{% block page_content %}
    This is sample content
{% endblock page_content %}

crm/templates/crm/admin_partner_create.html
{% extends "crm/base.html" %}

{% load static %}

{% block custom_css %}
    
{% endblock custom_css %}

{% block title %}
    Partner Create
{% endblock title %}


{% block page_title %}
    Partner Create
{% endblock page_title %}

{% block page_content %}

<div class="row">
    <div class="col-12 col-md-12 col-lg-12">
        <div class="card">
            <div class="card-header">
                <h4>Partner</h4>
            </div>
            <div class="card-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form  %}
                    <div class="form-group">
                        
                        <label>{{ field.label }}</label>
                        <input type="{{ field.field.widget.input_type }}" name="{{ field.name }}" id="{{ field.name }}" class="form-control">
                    
                        {% if field.errors %}
                        <div class="alert alert-danger" style="margin: 10px">
                            {{ field.errors }}
                        </div>
                        
                        {% endif %}
                    </div>
                    {% endfor %}

                    <div class="form-group">
                        <label>Profile picture</label>
                        <input type="file" name="profile_pic" id="profile_pic" class="form-control">
                    </div>


                    <div class="form-group">
                        <label>Birthdate</label>
                        <input type="text" name="date_of_birth" id="date_of_birth" class="form-control">
                    </div>

                    <div class="form-group">
                        <label>Phone</label>
                        <input type="text" name="phone_number" id="phone_number" class="form-control">
                    </div>

                    <div class="form-group">
                        <label>Address line 1</label>
                        <input type="text" name="address_line_1" id="address_line_1" class="form-control">
                    </div>

                    <div class="form-group">
                        <label>Address line 2</label>
                        <input type="text" name="address_line_2" id="address_line_2" class="form-control">
                    </div>

                    <div class="form-group">
                        <label>City</label>
                        <input type="text" name="address_town" id="address_town" class="form-control">
                    </div>

                    <div class="form-group">
                        <label>State</label>
                        <input type="text" name="address_region" id="address_region" class="form-control">
                    </div>

                    <div class="form-group">
                        <label>Country</label>
                        <input type="text" name="address_country" id="address_country" class="form-control">
                    </div>
                   
                    <div class="form-group">
                        <label>Zip code</label>
                        <input type="text" name="address_zip_code" id="address_zip_code" class="form-control">
                    </div>

                    <br>

                    <div class="form-group">
                        <label class="custom-switch mt-2">
                        <input type="checkbox" name="is_added_by_admin" class="custom-switch-input">
                        <span class="custom-switch-indicator"></span>
                        <span class="custom-switch-description">Is added by Admin?</span>
                      </label>
                    </div>

                    <button href="" type="submit" class="btn btn-primary btn-block">SAVE PARTNER</button>
                </form>
            </div>
        </div>
    </div>
</div>



{% endblock page_content %}

{% block custom_js %}

{% endblock custom_js %}

crm/templates/crm/admin_partner_list.html
{% extends "crm/base.html" %}

{% block custom_css %}
<style>
.circular_image {
  width: 150px;
  height: 150px;
  border-radius: 50%;
  float: left;
  overflow: hidden;
  background-color: blue;
  display:inline-block;
  vertical-align:center;
}
</style>
{% endblock custom_css %}
{% block title %}
    Partner List
{% endblock title %}

{% block page_title %}
    Partner List
{% endblock page_title %}

{% block page_content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="search-element">
                <div class="card">
                    <div class="card-body">

                        <div class="float-left">

                        
                            <ul class="list-unstyled list-unstyled-border list-unstyled-noborder">
                                <li class="media">                     
                                    <div class="media-body ml-3">
                                        <div class="media-links">
                                            SORTED BY : 
                                            <a href="{% url 'crm:admin_partner_list_view' %}?filter={{ filter }}&orderby=id">DATE ENTERED</a><div class="bullet"></div> 
                                            <a href="{% url 'crm:admin_partner_list_view' %}?filter={{ filter }}&orderby=auth_user_id__first_name">FIRSTNAME</a><div class="bullet"></div>
                                            <a href="{% url 'crm:admin_partner_list_view' %}?filter={{ filter }}&orderby=auth_user_id__last_name">LASTNAME  </a>
                                        </div>
                                    </div>
                                </li>

                            </ul>

                        </div>
                        <form method="GET">
                            <div class="input-group float-right">
                                <input type="search" class="form-control" placeholder="Search" aria-label="Search" aria-describedby="basic-addon2" name="filter" value="{{ filter }}">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit">Search</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
    {% for partner in partneruser_list %}
        <div class="col-12 col-sm-6 col-md-6 col-lg-3">
            <article class="article article-style-b">
      
                <div class="article-details">
                    <div class="article-title">
                         <dl class="row">

                            <dt class="col-sm-5">

                                <div class="circular_image">
                                    <img alt="image" src="/media/{{ partner.profile_pic }}" style="width: 100%;">
                                </div>
                               
                            </dt>
                            <dd class="col-sm-7 pt-3">
                                <span class="lead">{{ partner.auth_user_id.first_name }} {{ partner.auth_user_id.last_name }} </span><br>
                                @{{ partner.auth_user_id.username }}
                            </dd>
                        </dl>
                    </div>
                    
                    <dl class="row">

                        <dt class="col-sm-3">Email</dt>
                        <dd class="col-sm-9">{{ partner.auth_user_id.email }}</dd>

                        <dt class="col-sm-3">Birthdate</dt>
                        <dd class="col-sm-9">{{ partner.date_of_birth|date:"M d, Y" }}</dd>

                        <dt class="col-sm-3">Address</dt>
                        <dd class="col-sm-9">
                            
                                {% if partner.address_line_1 %}{{ partner.address_line_1 }}{% endif %}
                                {% if partner.address_line_2 %}, {{ partner.address_line_2 }}{% endif %}
                            <br>
                                {% if partner.address_town %}{{ partner.address_town }}{% endif %}
                                {% if partner.address_region %}, {{ partner.address_region }}{% endif %}
                            <br>
                                {% if partner.address_country %}{{ partner.address_country }}{% endif %}
                                {% if partner.address_zip_code %}, {{ partner.address_zip_code }}{% endif %}
                            
                        </dd>

                    </dl>
                    <div class="article-cta">
                        <label class="custom-switch mt-2 float-left">
                            <input type="checkbox" name="is_added_by_admin" onclick="return false;" class="custom-switch-input" {% if partner.is_added_by_admin %}checked{% endif %}>
                            <span class="custom-switch-indicator"></span>
                            <span class="custom-switch-description">Is added by Admin?</span>
                        </label>
                        <div class="user-item">
                            <div class="user-details">
                                <div class="user-cta float-right">
                                    <a href="{% url 'crm:admin_partner_update_view' partner.auth_user_id.id %}" class="btn btn-primary btn-round">Edit</a>
                                </div>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </article>
        </div>
    {% endfor %}
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <nav aria-label="partner Pagination">
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                                <li class="page-item"><a class="page-link" href="{% url 'crm:admin_partner_list_view' %}?filter={{ filter }}&orderby={{ orderby }}&page={{ page_obj.previous_page_number }}">Previous</a></li>
                            {% else %}
                                <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                            {% endif %}
                            {% for i in paginator.page_range %}
                                    <li class="page-item {% if i == page_obj.number %}active{% endif %}"><a class="page-link" href="{% url 'crm:admin_partner_list_view' %}?filter={{ filter }}&orderby={{ orderby }}&page={{ i }}">{{ i }}</a></li>
                            {% endfor %}
                            {% if page_obj.has_next %}
                                <li class="page-item"><a class="page-link" href="{% url 'crm:admin_partner_list_view' %}?filter={{ filter }}&orderby={{ orderby }}&page={{ page_obj.next_page_number }}">Next</a></li>
                            {% else %}
                                <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                            {% endif %}

                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
{% endblock page_content %}

crm/templates/crm/admin_partner_update.html
{% extends "crm/base.html" %}

{% load static %}

{% block custom_css %}
    
{% endblock custom_css %}

{% block title %}
    Partner Update
{% endblock title %}


{% block page_title %}
    Partner Update
{% endblock page_title %}

{% block page_content %}

<div class="row">
    <div class="col-12 col-md-12 col-lg-12">
        <div class="card">
            <div class="card-header">
                <h4>Partner</h4>
            </div>
            <div class="card-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form  %}
                    <div class="form-group">
                        
                        <label>{{ field.label }}</label>
                        <input value="{{ field.value }}" type="{{ field.field.widget.input_type }}" name="{{ field.name }}" id="{{ field.name }}" class="form-control">
                    
                        {% if field.errors %}
                        <div class="alert alert-danger" style="margin: 10px">
                            {{ field.errors }}
                        </div>
                        
                        {% endif %}
                    </div>
                    {% endfor %}

                    <div class="form-group">
                        <label>Profile picture</label>
                        <input type="file" name="profile_pic" id="profile_pic" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>Current profile image</label><br>
                        <img src="{{ partneruser.profile_pic.url }}" style="height: 150px" class="img-thumbnail">
                    </div>


                    <div class="form-group">
                        <label>Birthdate</label>
                        <input value="{{ partneruser.date_of_birth|date:"Y-m-d" }}" type="text" name="date_of_birth" id="date_of_birth" class="form-control">
                    </div>

                    <div class="form-group">
                        <label>Phone</label>
                        <input value="{{ partneruser.phone_number }}" type="text" name="phone_number" id="phone_number" class="form-control">
                    </div>

                    <div class="form-group">
                        <label>Address line 1</label>
                        <input value="{{ partneruser.address_line_1 }}" type="text" name="address_line_1" id="address_line_1" class="form-control">
                    </div>

                    <div class="form-group">
                        <label>Address line 2</label>
                        <input value="{{ partneruser.address_line_2 }}" type="text" name="address_line_2" id="address_line_2" class="form-control">
                    </div>

                    <div class="form-group">
                        <label>City</label>
                        <input value="{{ partneruser.address_town }}" type="text" name="address_town" id="address_town" class="form-control">
                    </div>

                    <div class="form-group">
                        <label>State</label>
                        <input value="{{ partneruser.address_region }}" type="text" name="address_region" id="address_region" class="form-control">
                    </div>

                    <div class="form-group">
                        <label>Country</label>
                        <input value="{{ partneruser.address_country }}" type="text" name="address_country" id="address_country" class="form-control">
                    </div>
                   
                    <div class="form-group">
                        <label>Zip code</label>
                        <input value="{{ partneruser.address_zip_code }}" type="text" name="address_zip_code" id="address_zip_code" class="form-control">
                    </div>

                    <br>

                    <div class="form-group">
                        <label class="custom-switch mt-2">
                        <input type="checkbox" name="is_added_by_admin" class="custom-switch-input" {% if partneruser.is_added_by_admin %}checked{% endif %}>
                        <span class="custom-switch-indicator"></span>
                        <span class="custom-switch-description">Is added by Admin?</span>
                      </label>
                    </div>

                    <button href="" type="submit" class="btn btn-primary btn-block">UPDATE PARTNER</button>
                </form>
            </div>
        </div>
    </div>
</div>



{% endblock page_content %}

{% block custom_js %}

{% endblock custom_js %}