crm/urls.py
from django.urls import path
from .views import (
    admin_dashboard_view, 
    educ_media_upload_view,
    lc_media_upload_view,
    other_media_upload_view,
    UserPartnerCreateView,
    UserPartnerListView,
    UserPartnerUpdateView,
    UserPartnerResumeCreateView,
    UserPartnerResumeUpdateView,
    UserPartnerWithResumeListView,
    UserPartnerMediaUpload,
)

app_name = 'crm'

urlpatterns = [

    # Dashboard
    path('admin/dashboard/', admin_dashboard_view, name='admin_dashboard_view'),

    path('educ_media_upload/', educ_media_upload_view, name='educ_media_upload'),
    path('lc_media_upload/', lc_media_upload_view, name='lc_media_upload'),
    path('other_media_upload/', other_media_upload_view, name='other_media_upload'),

    path('admin/partner_create/', UserPartnerCreateView.as_view(), name='admin_partner_create_view'),
    path('admin/partner_update/<slug:pk>/', UserPartnerUpdateView.as_view(), name='admin_partner_update_view'),
    path('admin/partner_list/', UserPartnerListView.as_view(), name='admin_partner_list_view'),
    path('admin/partner_resume_create/<slug:pk>/', UserPartnerResumeCreateView.as_view(), name='admin_partner_resume_create_view'),
    path('admin/partner_resume_update/<slug:pk>/', UserPartnerResumeUpdateView.as_view(), name='admin_partner_resume_update_view'),
    path('admin/partner_with_resume_list/', UserPartnerWithResumeListView.as_view(), name='admin_partner_with_resume_list_view'),
    path('admin/partner_media_upload/<slug:pk>/', UserPartnerMediaUpload.as_view(), name='admin_partner_media_upload_view'),

]

sassist/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import login_view, logout_view


urlpatterns = [
    path('admin/', admin.site.urls),

    # Login
    path('login/', login_view, name='login_view'),
    path('logout/', logout_view, name='logout_view'),

    path('crm/', include('crm.urls', namespace='crm')),
    path('partners/', include('partners.urls', namespace='partners')),
    path('jobs/', include('jobs.urls', namespace='jobs')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/views.py
import os

from datetime import date

from django.contrib.messages.views import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.core.serializers import serialize
from django.db.models import Q, fields
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import CreateView, DeleteView, ListView, UpdateView, View

from profiles.models import CustomUser, PartnerUser

from partners.models import (
    PartnerEducation,
    PartnerLicense,
    PartnerCertification,
    PartnerReference,
    PartnerSkill,
    PartnerCoverLetter,
    PartnerEducationMedia,
    PartnerLCMedia,
    PartnerOtherMedia, 
    PartnerProfessionalSummary,
    PartnerWorkHistory,
)

def admin_dashboard_view(request):
    return render(request, 'crm/admin_dashboard.html')

def educ_media_upload_view(request):
    if request.method == 'POST':
        media_file_name = request.FILES.get('file').name
        media_file = request.FILES.get('file')

        # TODO: hash the file size for extra validation in duplication
        file_format = ''

        if media_file_name.endswith('.jpg') or media_file_name.endswith('.jpeg'):
            file_format = 1
        if media_file_name.endswith('.png'):
            file_format = 2
        if media_file_name.endswith('.pdf'):
            file_format = 3
        
        partner_id = request.POST.get('partner_id')
        partner_instance = PartnerUser.objects.get(id=partner_id)
        obj, created = PartnerEducationMedia.objects.get_or_create(auth_user_id=partner_instance, media_filename=media_file_name, media_format=file_format)

        if created:
            obj.media_content = media_file
            obj.save()

            qs_ed = PartnerEducationMedia.objects.filter(auth_user_id=partner_instance)
            qs_lc = PartnerLCMedia.objects.filter(auth_user_id=partner_instance)
            qs_od = PartnerOtherMedia.objects.filter(auth_user_id=partner_instance)
            data_ed = serialize("json", qs_ed, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))
            data_lc = serialize("json", qs_lc, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))
            data_od = serialize("json", qs_od, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))

            return JsonResponse({'ex': False, 'data_ed': data_ed, 'data_lc': data_lc, 'data_od': data_od})
        
        else:

            qs_ed = PartnerEducationMedia.objects.filter(auth_user_id=partner_instance)
            qs_lc = PartnerLCMedia.objects.filter(auth_user_id=partner_instance)
            qs_od = PartnerOtherMedia.objects.filter(auth_user_id=partner_instance)
            data_ed = serialize("json", qs_ed, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))
            data_lc = serialize("json", qs_lc, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))
            data_od = serialize("json", qs_od, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))

            return JsonResponse({'ex': True, 'data_ed': data_ed, 'data_lc': data_lc, 'data_od': data_od})

    return HttpResponse()


def lc_media_upload_view(request):
    if request.method == 'POST':
        media_file_name = request.FILES.get('file').name
        media_file = request.FILES.get('file')

        # TODO: hash the file size for extra validation in duplication
        file_format = ''

        if media_file_name.endswith('.jpg') or media_file_name.endswith('.jpeg'):
            file_format = 1
        if media_file_name.endswith('.png'):
            file_format = 2
        if media_file_name.endswith('.pdf'):
            file_format = 3
        
        partner_id = request.POST.get('partner_id')
        partner_instance = PartnerUser.objects.get(id=partner_id)
        obj, created = PartnerLCMedia.objects.get_or_create(auth_user_id=partner_instance, media_filename=media_file_name, media_format=file_format)

        if created:
            obj.media_content = media_file
            obj.save()

            qs_ed = PartnerEducationMedia.objects.filter(auth_user_id=partner_instance)
            qs_lc = PartnerLCMedia.objects.filter(auth_user_id=partner_instance)
            qs_od = PartnerOtherMedia.objects.filter(auth_user_id=partner_instance)
            data_ed = serialize("json", qs_ed, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))
            data_lc = serialize("json", qs_lc, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))
            data_od = serialize("json", qs_od, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))

            return JsonResponse({'ex': False, 'data_ed': data_ed, 'data_lc': data_lc, 'data_od': data_od})
        
        else:

            qs_ed = PartnerEducationMedia.objects.filter(auth_user_id=partner_instance)
            qs_lc = PartnerLCMedia.objects.filter(auth_user_id=partner_instance)
            qs_od = PartnerOtherMedia.objects.filter(auth_user_id=partner_instance)
            data_ed = serialize("json", qs_ed, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))
            data_lc = serialize("json", qs_lc, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))
            data_od = serialize("json", qs_od, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))

            return JsonResponse({'ex': True, 'data_ed': data_ed, 'data_lc': data_lc, 'data_od': data_od})

    return HttpResponse()

def other_media_upload_view(request):
    if request.method == 'POST':
        media_file_name = request.FILES.get('file').name
        media_file = request.FILES.get('file')

        # TODO: hash the file size for extra validation in duplication
        file_format = ''

        if media_file_name.endswith('.jpg') or media_file_name.endswith('.jpeg'):
            file_format = 1
        if media_file_name.endswith('.png'):
            file_format = 2
        if media_file_name.endswith('.pdf'):
            file_format = 3
        
        partner_id = request.POST.get('partner_id')
        partner_instance = PartnerUser.objects.get(id=partner_id)
        obj, created = PartnerOtherMedia.objects.get_or_create(auth_user_id=partner_instance, media_filename=media_file_name, media_format=file_format)

        if created:
            obj.media_content = media_file
            obj.save()

            qs_ed = PartnerEducationMedia.objects.filter(auth_user_id=partner_instance)
            qs_lc = PartnerLCMedia.objects.filter(auth_user_id=partner_instance)
            qs_od = PartnerOtherMedia.objects.filter(auth_user_id=partner_instance)
            data_ed = serialize("json", qs_ed, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))
            data_lc = serialize("json", qs_lc, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))
            data_od = serialize("json", qs_od, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))

            return JsonResponse({'ex': False, 'data_ed': data_ed, 'data_lc': data_lc, 'data_od': data_od})
        
        else:

            qs_ed = PartnerEducationMedia.objects.filter(auth_user_id=partner_instance)
            qs_lc = PartnerLCMedia.objects.filter(auth_user_id=partner_instance)
            qs_od = PartnerOtherMedia.objects.filter(auth_user_id=partner_instance)
            data_ed = serialize("json", qs_ed, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))
            data_lc = serialize("json", qs_lc, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))
            data_od = serialize("json", qs_od, fields=('id', 'media_filename', 'media_format', 'media_content', 'created'))

            return JsonResponse({'ex': True, 'data_ed': data_ed, 'data_lc': data_lc, 'data_od': data_od})

    return HttpResponse()


class UserPartnerCreateView(SuccessMessageMixin, CreateView):

    model = CustomUser
    template_name = 'crm/admin_partner_create.html'
    success_message = 'Partner added successfully!'
    fields = (
        'first_name',
        'last_name',
        'email',
        'username',
        'password',
    )

    def form_valid(self, form):

        user = form.save(commit=False)
        user.is_active = True
        user.user_type = 3
        user.set_password(form.cleaned_data['password'])
        user.save()

        # Saving user.partnerusers
        user.partnerusers.profile_pic = self.request.FILES['profile_pic']
        user.partnerusers.date_of_birth = date(*map(int, self.request.POST.get('date_of_birth').split('-')))
     
        user.partnerusers.phone_number = self.request.POST.get('phone_number')
        user.partnerusers.address_line_1 = self.request.POST.get('address_line_1')
        user.partnerusers.address_line_2 = self.request.POST.get('address_line_2')
        user.partnerusers.address_town = self.request.POST.get('address_town')
        user.partnerusers.address_region = self.request.POST.get('address_region')
        user.partnerusers.address_country = self.request.POST.get('address_country')
        user.partnerusers.address_zip_code = self.request.POST.get('address_zip_code')

        is_added_by_admin = False

        if self.request.POST.get('is_added_by_admin') == 'on':
            is_added_by_admin = True

        user.partnerusers.is_added_by_admin = is_added_by_admin
        user.save()

        messages.success(self.request, 'Partner user created')

        return HttpResponseRedirect(reverse('crm:admin_partner_list_view'))


class UserPartnerUpdateView(SuccessMessageMixin, UpdateView):

    model = CustomUser
    template_name = 'crm/admin_partner_update.html'

templates/crm/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title>
    CarePartneRx | {% block title %}{% endblock title %}
  </title>

  <!-- General CSS Files -->
  <link rel="stylesheet" href="{% static 'crm/modules/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'crm/modules/fontawesome/css/all.min.css' %}">

  <!-- CSS Libraries -->
  <link rel="stylesheet" href="{% static 'crm/modules/jqvmap/dist/jqvmap.min.css' %}">
  <link rel="stylesheet" href="{% static 'crm/modules/summernote/summernote-bs4.css' %}">
  <link rel="stylesheet" href="{% static 'crm/modules/owlcarousel2/dist/assets/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'crm/modules/owlcarousel2/dist/assets/owl.theme.default.min.css' %}">


  <!-- Dropzone js -->
  <link rel="stylesheet" href="{% static 'dropzone.css' %}">

  <!-- Template CSS -->
  <link rel="stylesheet" href="{% static 'crm/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'crm/css/components.css' %}">
  <link rel="stylesheet" href="{% static 'custom.css' %}">


  {% block custom_css %}
  {% endblock custom_css %}
</head>

<body>
  <div id="app">
    <div class="main-wrapper main-wrapper-1">
      {% include "crm/navbar.html" %}

      {% include "crm/sidebar.html" with id=form.instance.id %}

      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>{% block page_title %}{% endblock page_title %}</h1>
            </div>
            {% if messages %}
                {% for message in messages %}
                {% if message.tags == "success" %}
                  <div id="success-alert" class="alert alert-success">
                  {{ message }}
                  </div>
                {% endif %}
                {% if message.tags == "danger" %}
                  <div class="alert alert-danger">
                  {{ message }}
                  </div>
                {% endif %}
              {% endfor %}
            
            {% endif %}
            {% block page_content %}
            
            {% endblock page_content %}
        </section>
      </div>
      {% include "crm/footer.html" %}
    </div>
  </div>

  <!-- General JS Scripts -->
    <script src="{% static 'crm/modules/jquery.min.js' %}" defer></script>
    <script src="{% static 'crm/modules/popper.js' %}" defer></script>
    <script src="{% static 'crm/modules/tooltip.js' %}" defer></script>
    <script src="{% static 'crm/modules/bootstrap/js/bootstrap.min.js' %}" defer></script>
    <script src="{% static 'crm/modules/nicescroll/jquery.nicescroll.min.js' %}" defer></script>
    <script src="{% static 'crm/modules/moment.min.js' %}" defer></script>
    <script src="{% static 'crm/js/stisla.js' %}" defer></script>
    
    <!-- JS Libraies -->
    <script src="{% static 'crm/modules/jquery.sparkline.min.js' %}" defer></script>
    <script src="{% static 'crm/modules/chart.min.js' %}" defer></script>
    <script src="{% static 'crm/modules/owlcarousel2/dist/owl.carousel.min.js' %}" defer></script>
    <script src="{% static 'crm/modules/summernote/summernote-bs4.js' %}" defer></script>
    <script src="{% static 'crm/modules/chocolat/dist/js/jquery.chocolat.min.js' %}" defer></script>

    <!-- Page Specific JS File -->
    {% comment %} <script src="{% static 'crm/js/page/index.js' %}"></script> {% endcomment %}
    
    <!-- Template JS File -->
    <script src="{% static 'crm/js/scripts.js' %}" defer></script> 
    <script src="{% static 'crm/js/custom.js' %}" defer></script>  
    <script src="{% static 'dropzone.js' %}" defer></script>

  {% block custom_js %}
  {% endblock custom_js %}
</body>
</html>

templates/crm/navbar.html
{% load static %}
<div class="navbar-bg"></div>
<nav class="navbar navbar-expand-lg main-navbar">
    <form class="form-inline mr-auto">
        <ul class="navbar-nav mr-3">
        <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
        <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a></li>
        </ul>
        <div class="search-element">
        
        
        </div>
    </form>
    <ul class="navbar-nav navbar-right"> 
        <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
        <img alt="image" src="{{ request.user.adminusers.profile_pic.url }}" class="rounded-circle mr-1">
        <div class="d-sm-none d-lg-inline-block">Hi, {{ request.user.first_name }} {{ request.user.last_name }}</div></a>
        <div class="dropdown-menu dropdown-menu-right">
            <div class="dropdown-title">Logged in 5 min ago</div>
            <a href="features-profile.html" class="dropdown-item has-icon">
            <i class="far fa-user"></i> Profile
            </a>
            <a href="features-activities.html" class="dropdown-item has-icon">
            <i class="fas fa-bolt"></i> Activities
            </a>
            <a href="features-settings.html" class="dropdown-item has-icon">
            <i class="fas fa-cog"></i> Settings
            </a>
            <div class="dropdown-divider"></div>
            <a href="{% url 'crm:logout_view' %}" class="dropdown-item has-icon text-danger">
            <i class="fas fa-sign-out-alt"></i> Logout
            </a>
        </div>
        </li>
    </ul>
</nav>

templates/crm/sidebar.html
{% load static %}

{% comment %} Partners{% endcomment %}
{% url 'crm:admin_partner_list_view' as admin_partner_list %}
{% url 'crm:admin_partner_create_view' as admin_partner_create %}
{% url 'crm:admin_partner_update_view' id as admin_partner_update %}
{% url 'crm:admin_partner_resume_create_view' partner_user.id as admin_partner_resume_create %}
{% url 'crm:admin_partner_resume_update_view' partner_user.id as admin_partner_resume_update %}
{% url 'crm:admin_partner_with_resume_list_view' as admin_partner_with_resume_list %}
{% url 'crm:admin_partner_media_upload_view' partner_user.id as admin_partner_media_upload %}

<div class="main-sidebar sidebar-style-2">
    <aside id="sidebar-wrapper">
        <div class="sidebar-brand mt-2">
            <img src="{% static 'crm/img/logo.png' %}" alt="logo" width="50" class="">
        </div>
        <div class="sidebar-brand sidebar-brand-sm">
            <a href="index.html">CPRx</a>
        </div>
        <ul class="sidebar-menu">
            <li class="menu-header">Dashboard</li>

            {% comment %} Partners Menu {% endcomment %}
            <li class="dropdown {% if request.path == admin_partner_list %}active{% endif %}{% if request.path == admin_partner_create %}active{% endif %}{% if request.path == admin_partner_update %}active{% endif %}{% if request.path == admin_partner_with_resume_list %}active{% endif %}{% if request.path == admin_partner_resume_create %}active{% endif %}{% if request.path == admin_partner_resume_update %}active{% endif %}{% if request.path == admin_partner_media_upload %}active{% endif %}">
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-users"></i><span>Partners</span></a>
                <ul class="dropdown-menu">
                    <li class='{% if request.path == admin_partner_list %}active{% endif %}'><a class="nav-link" href="{% url 'crm:admin_partner_list_view' %}">All Partners</a></li>
                    <li class='{% if request.path == admin_partner_create %}active{% endif %}'><a class="nav-link" href="{% url 'crm:admin_partner_create_view' %}">Add Partner</a></li>
                    <li class='{% if request.path == admin_partner_with_resume_list %}active{% endif %}'><a class="nav-link" href="{% url 'crm:admin_partner_with_resume_list_view' %}">Resume List</a></li>
                </ul>
            </li>

            <li class="dropdown">
                <a href="#" class="nav-link has-dropdown"><i class="fab fa-accessible-icon"></i><span>Patients</span></a>
                
            </li>

            <li class="dropdown">
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-envelope"></i><span>Messages</span></a>
                
            </li>

            <li class="dropdown">
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-file-signature"></i><span>Contracts</span></a>
                
            </li>

            <li class="dropdown">
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-user-md"></i><span>Healthcare Jobs</span></a>
               
            </li>

            <li class="dropdown">
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-warehouse"></i><span>Facilities</span></a>
                
            </li>

            <li class="dropdown">
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-user-injured"></i><span>Insurances</span></a>
                
            </li>

            <li class="dropdown">
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-hand-holding-usd"></i><span>Financials</span></a>
                
            </li>



        <div class="mt-4 mb-4 p-3 hide-sidebar-mini">
            <a href="{% url 'logout_view' %}" class="btn btn-primary btn-lg btn-block btn-icon-split">
            <i class="fas fa-sign-out-alt"></i> LOGOUT
            </a>
        </div>   
    </aside>
</div>