crm/urls.py
from django.urls import path
from .views import (
    admin_dashboard_view, 
    educ_media_upload_view,
    lc_media_upload_view,
    other_media_upload_view,
    UserPartnerCreateView,
    UserPartnerListView,
    UserPartnerUpdateView,
    UserPartnerResumeCreateView,
    UserPartnerResumeUpdateView,
    UserPartnerWithResumeListView,
    UserPartnerMediaUpload,
)

app_name = 'crm'

urlpatterns = [

    # Dashboard
    path('admin/dashboard/', admin_dashboard_view, name='admin_dashboard_view'),

    path('educ_media_upload/', educ_media_upload_view, name='educ_media_upload'),
    path('lc_media_upload/', lc_media_upload_view, name='lc_media_upload'),
    path('other_media_upload/', other_media_upload_view, name='other_media_upload'),

    path('admin/partner_create/', UserPartnerCreateView.as_view(), name='admin_partner_create_view'),
    path('admin/partner_update/<slug:pk>/', UserPartnerUpdateView.as_view(), name='admin_partner_update_view'),
    path('admin/partner_list/', UserPartnerListView.as_view(), name='admin_partner_list_view'),
    path('admin/partner_resume_create/<slug:pk>/', UserPartnerResumeCreateView.as_view(), name='admin_partner_resume_create_view'),
    path('admin/partner_resume_update/<slug:pk>/', UserPartnerResumeUpdateView.as_view(), name='admin_partner_resume_update_view'),
    path('admin/partner_with_resume_list/', UserPartnerWithResumeListView.as_view(), name='admin_partner_with_resume_list_view'),
    path('admin/partner_media_upload/<slug:pk>/', UserPartnerMediaUpload.as_view(), name='admin_partner_media_upload_view'),

]

jobs/urls.py
from django.urls import path

from .views import JobView

app_name = 'jobs'

urlpatterns = [
    # Find jobs
    path('', JobView.as_view(), name='jobs_view'),
]

partners/urls.py
from django.urls import path

from .views import (
    educ_media_upload_view,
    lc_media_upload_view,
    other_media_upload_view,

    PartnerDashboardView,
    PartnerUpdateView,
    PartnerResumePanelView,
    PartnerEducationView,
    PartnerLicensesView,
    PartnerCertificationsView,
    PartnerReferencesView,
    PartnerSkillsView,
    PartnerWorkExperiencesView,
    PartnerProfessionalSummaryView,
    PartnerCoverLetterView,
    PartnerMediaUpload,

    PartnerEducationUpdateView,
    PartnerLicensesUpdateView,
    PartnerCertificationsUpdateView,
    PartnerReferencesUpdateView,
)

app_name = 'partners'

urlpatterns = [

    # Dashboard
    path('dashboard/', PartnerDashboardView.as_view(), name='partner_dashboard_view'),

    # Media upload functions
    path('educ_media_upload/', educ_media_upload_view, name='educ_media_upload'),
    path('lc_media_upload/', lc_media_upload_view, name='lc_media_upload'),
    path('other_media_upload/', other_media_upload_view, name='other_media_upload'),

    # Update partner
    path('account/update/', PartnerUpdateView.as_view(), name='partner_account_update_view'),

    # Resume panel
    path('resume-panel/', PartnerResumePanelView.as_view(), name='partner_resume_panel_view'),

    path('my-education/', PartnerEducationView.as_view(), name='partner_education_view'),
    path('my-licenses/', PartnerLicensesView.as_view(), name='partner_licenses_view'),
    path('my-certifications/', PartnerCertificationsView.as_view(), name='partner_certifications_view'),
    path('my-references/', PartnerReferencesView.as_view(), name='partner_references_view'),
    path('my-skills/', PartnerSkillsView.as_view(), name='partner_skills_view'),
    path('my-work-experiences/', PartnerWorkExperiencesView.as_view(), name='partner_work_experiences_view'),
    path('my-professional-summary/', PartnerProfessionalSummaryView.as_view(), name='partner_professional_summary_view'),
    path('my-cover-letter/', PartnerCoverLetterView.as_view(), name='partner_cover_letter_view'),
    path('my-documents/', PartnerMediaUpload.as_view(), name='partner_media_upload_view'),

    path('my-education/update/', PartnerEducationUpdateView.as_view(), name='partner_education_update_view'),
    path('my-licenses/update/', PartnerLicensesUpdateView.as_view(), name='partner_licenses_update_view'),
    path('my-certifications/update/', PartnerCertificationsUpdateView.as_view(), name='partner_certifications_update_view'),
    path('my-references/update/', PartnerReferencesUpdateView.as_view(), name='partner_references_update_view'),


]

partners/views.py
import os

from datetime import date

from django.contrib.messages.views import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.core.serializers import serialize
from django.db.models import Q, fields
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import CreateView, DeleteView, ListView, UpdateView, View

from profiles.models import CustomUser, PartnerUser
from .models import (
    PartnerEducation,
    PartnerLicense,
    PartnerCertification,
    PartnerReference,
    PartnerSkill,
    PartnerCoverLetter,
    PartnerEducationMedia,
    PartnerLCMedia,
    PartnerOtherMedia, 
    PartnerProfessionalSummary,
    PartnerWorkHistory,
)
from .utils import get_progress_value


class PartnerDashboardView(View):

    def get(self, request, *args, **kwargs):

        partner_user = PartnerUser.objects.get(auth_user_id=request.user.id)
        context = {
            'partner_user': partner_user,
        }

        return render(request, 'partners/partner_dashboard.html', context)


class PartnerUpdateView(View):

    def get(self, request, *args, **kwargs):


        partner_user_basic = CustomUser.objects.get(id=request.user.id)
        partner_user = PartnerUser.objects.get(auth_user_id=request.user.id)
        context = {
            'partner_user_basic': partner_user_basic,
            'partner_user': partner_user,
        }

        return render(request, 'partners/partner_update.html', context)

    def post(self, request, *args, **kwargs):
        
        partner_user_basic = CustomUser.objects.get(id=request.user.id)
        partner_user = PartnerUser.objects.get(auth_user_id=request.user.id)

        partner_user_basic.first_name = self.request.POST.get('first_name')
        partner_user_basic.last_name = self.request.POST.get('last_name')

        if self.request.FILES.get('profile_pic', False):
            partner_user.profile_pic = self.request.FILES['profile_pic']

        partner_user.date_of_birth = date(*map(int, self.request.POST.get('date_of_birth').split('-')))
     
        partner_user.phone_number = self.request.POST.get('phone_number')
        partner_user.address_line_1 = self.request.POST.get('address_line_1')
        partner_user.address_line_2 = self.request.POST.get('address_line_2')
        partner_user.address_town = self.request.POST.get('address_town')
        partner_user.address_region = self.request.POST.get('address_region')
        partner_user.address_country = self.request.POST.get('address_country')
        partner_user.address_zip_code = self.request.POST.get('address_zip_code')

        partner_user_basic.save()
        partner_user.save()

        return HttpResponse("Saved")


class PartnerResumePanelView(View):

    def get(self, request, *args, **kwargs):

        partner_user = PartnerUser.objects.get(auth_user_id=request.user.id)

        progress_mark = 10

        try:
            partner_professional_summary = PartnerProfessionalSummary.objects.get(auth_user_id=partner_user.id)
        except:
            partner_professional_summary = None

        try:
            partner_cover = PartnerCoverLetter.objects.get(auth_user_id=partner_user.id)
        except:
            partner_cover = None

        partner_education = partner_user.partnereducations.all()
        partner_licenses = partner_user.partnerlicenses.all()
        partner_certifications = partner_user.partnercertifications.all()
        partner_skills = partner_user.partnerskills.all()
        partner_works = partner_user.partnerworkhistories.all()
        partner_references = partner_user.partnerreferences.all()
        
        context = {
            'partner_user': partner_user,
            'partner_professional_summary': partner_professional_summary,
            'partner_education': partner_education,
            'partner_licenses': partner_licenses,
            'partner_certifications': partner_certifications,
            'partner_skills': partner_skills,
            'partner_works': partner_works,
            'partner_references': partner_references,
            'partner_cover': partner_cover,
            'progress_mark': get_progress_value(request.user.id)
        }

        return render(request, 'partners/partner_resume_panel.html', context)


class PartnerEducationView(View):

    def get(self, request, *args, **kwargs):

        partner_user = PartnerUser.objects.get(auth_user_id=request.user.id)
        context = {
            'partner_user': partner_user,
            'partner_education': partner_user.partnereducations.all()
        }

        return render(request, 'partners/partner_education.html', context)

    def post(self, request, *args, **kwargs):

        partner_user = PartnerUser.objects.get(auth_user_id=request.user.id)

        # PartnerEducation
        pe_degree_type = request.POST.getlist('degree[]')
        pe_school_name = request.POST.getlist('school[]')
        pe_field_name = request.POST.getlist('field[]')
        pe_date_graduated = request.POST.getlist('graduated[]')
        pe_school_address = request.POST.getlist('school_address[]')

        # Saving education
        i = 0
        for degree_type in pe_degree_type:
            education_obj = PartnerEducation(
                degree_type=degree_type,
                school_name=pe_school_name[i],
                field_name=pe_field_name[i],
                date_graduated=pe_date_graduated[i],
                school_address=pe_school_address[i],
                auth_user_id=partner_user
            )
            education_obj.save()
            i += 1

        return HttpResponse("Saved")


class PartnerLicensesView(View):

    def get(self, request, *args, **kwargs):

        partner_user = PartnerUser.objects.get(auth_user_id=request.user.id)
        context = {
            'partner_user': partner_user,
            'partner_licenses': partner_user.partnerlicenses.all()
        }

        return render(request, 'partners/partner_licenses.html', context)

    def post(self, request, *args, **kwargs):

        partner_user = PartnerUser.objects.get(auth_user_id=request.user.id)

        # PartnerLicense
        pl_license_name = request.POST.getlist('license_name[]')
        pl_license_code = request.POST.getlist('license_code[]')
        pl_expiration_date = request.POST.getlist('license_expiration_date[]')
        pl_address_acquired = request.POST.getlist('license_address[]')
        pl_is_compact = request.POST.getlist('license_is_compact[]')

        # Saving licenses
        i = 0
        for license_name in pl_license_name:
            license_obj = PartnerLicense(
                license_name=license_name,
                license_code=pl_license_code[i],
                expiration_date=pl_expiration_date[i],
                address_acquired=pl_address_acquired[i],
                is_compact=pl_is_compact[i],
                auth_user_id=partner_user
            )
            license_obj.save()
            i += 1

        return HttpResponse("Saved")


class PartnerCertificationsView(View):

    def get(self, request, *args, **kwargs):

        partner_user = PartnerUser.objects.get(auth_user_id=request.user.id)
        context = {
            'partner_user': partner_user,
            'partner_certifications': partner_user.partnercertifications.all()
        }

        return render(request, 'partners/partner_certifications.html', context)

    def post(self, request, *args, **kwargs):

        partner_user = PartnerUser.objects.get(auth_user_id=request.user.id)

        # PartnerCertification
        pc_cert_name = request.POST.getlist('certification_name[]')
        pc_cert_code = request.POST.getlist('certification_code[]')
        pc_expiration_date = request.POST.getlist('certification_expiration_date[]')
        pc_address_acquired = request.POST.getlist('certification_address[]')

        # Saving certifications
        i = 0
        for cert_name in pc_cert_name:
            cert_obj = PartnerCertification(
                cert_name=cert_name,
                cert_code=pc_cert_code[i],
                expiration_date=pc_expiration_date[i],
                address_acquired=pc_address_acquired[i],
                auth_user_id=partner_user
            )
            cert_obj.save()
            i += 1

        return HttpResponse("Saved")


class PartnerReferencesView(View):

    def get(self, request, *args, **kwargs):

        partner_user = PartnerUser.objects.get(auth_user_id=request.user.id)
        context = {
            'partner_user': partner_user,
            'partner_references': partner_user.partnerreferences.all()
        }

        return render(request, 'partners/partner_references.html', context)

    def post(self, request, *args, **kwargs):

        partner_user = PartnerUser.objects.get(auth_user_id=request.user.id)

        # PartnerReference
        pr_name = request.POST.getlist('reference_name[]')
        pr_position = request.POST.getlist('reference_position[]')
        pr_phone_number = request.POST.getlist('reference_phone_number[]')
        pr_email = request.POST.getlist('reference_email[]')
        pr_office_name = request.POST.getlist('reference_office_name[]')
        pr_office_address = request.POST.getlist('reference_office_address[]')
        pr_start_date = request.POST.getlist('reference_start_date[]')
        pr_end_date = request.POST.getlist('reference_end_date[]')

        # Saving references
        i = 0
        for reference in pr_name:
            reference_obj = PartnerReference(
                name=reference,
                position=pr_position[i],
                phone_number=pr_phone_number[i],
                email=pr_email[i],
                office_name=pr_office_name[i],
                office_address=pr_office_address[i],
                start_date=pr_start_date[i],

templates/partners/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title>
    CarePartneRx | {% block title %}{% endblock title %}
  </title>

  <!-- General CSS Files -->
  <link rel="stylesheet" href="{% static 'partners/modules/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'partners/modules/fontawesome/css/all.min.css' %}">

  <!-- CSS Libraries -->
  <link rel="stylesheet" href="{% static 'partners/modules/jqvmap/dist/jqvmap.min.css' %}">
  <link rel="stylesheet" href="{% static 'partners/modules/summernote/summernote-bs4.css' %}">
  <link rel="stylesheet" href="{% static 'partners/modules/owlcarousel2/dist/assets/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'partners/modules/owlcarousel2/dist/assets/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'partners/modules/ionicons/css/ionicons.min.css' %}">


  <!-- Dropzone js -->
  <link rel="stylesheet" href="{% static 'dropzone.css' %}">

  <!-- Template CSS -->
  <link rel="stylesheet" href="{% static 'partners/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'partners/css/components.css' %}">
  <link rel="stylesheet" href="{% static 'custom.css' %}">


  {% block custom_css %}
  {% endblock custom_css %}
</head>

<body>
  <div id="app">
    <div class="main-wrapper main-wrapper-1">
      {% include "partners/navbar.html" %}

      {% include "partners/sidebar.html" with id=form.instance.id %}

      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>{% block page_title %}{% endblock page_title %}</h1>
            </div>
            {% if messages %}
                {% for message in messages %}
                {% if message.tags == "success" %}
                  <div id="success-alert" class="alert alert-success">
                  {{ message }}
                  </div>
                {% endif %}
                {% if message.tags == "danger" %}
                  <div class="alert alert-danger">
                  {{ message }}
                  </div>
                {% endif %}
              {% endfor %}
            
            {% endif %}
            {% block page_content %}
            
            {% endblock page_content %}
        </section>
      </div>
      {% include "partners/footer.html" %}
    </div>
  </div>

  <!-- General JS Scripts -->
    <script src="{% static 'partners/modules/jquery.min.js' %}" defer></script>
    <script src="{% static 'partners/modules/popper.js' %}" defer></script>
    <script src="{% static 'partners/modules/tooltip.js' %}" defer></script>
    <script src="{% static 'partners/modules/bootstrap/js/bootstrap.min.js' %}" defer></script>
    <script src="{% static 'partners/modules/nicescroll/jquery.nicescroll.min.js' %}" defer></script>
    <script src="{% static 'partners/modules/moment.min.js' %}" defer></script>
    <script src="{% static 'partners/js/stisla.js' %}" defer></script>
    
    <!-- JS Libraies -->
    <script src="{% static 'partners/modules/jquery.sparkline.min.js' %}" defer></script>
    <script src="{% static 'partners/modules/chart.min.js' %}" defer></script>
    <script src="{% static 'partners/modules/owlcarousel2/dist/owl.carousel.min.js' %}" defer></script>
    <script src="{% static 'partners/modules/summernote/summernote-bs4.js' %}" defer></script>
    <script src="{% static 'partners/modules/chocolat/dist/js/jquery.chocolat.min.js' %}" defer></script>

    <!-- Page Specific JS File -->
    {% comment %} <script src="{% static 'partners/js/page/index.js' %}"></script> {% endcomment %}
    
    <!-- Template JS File -->
    <script src="{% static 'partners/js/scripts.js' %}" defer></script> 
    <script src="{% static 'partners/js/custom.js' %}" defer></script>  
    <script src="{% static 'dropzone.js' %}" defer></script>
    <script src="{% static 'partners/js/page/modules-ion-icons.js' %}" defer></script>

  {% block custom_js %}
  {% endblock custom_js %}
</body>
</html>

templates/partners/footer.html
<footer class="main-footer">
    <div class="footer-left">
        Copyright &copy; 2021 <div class="bullet"></div>Primo Healthcare Services, LLC
    </div>
    <div class="footer-right">
        
    </div>
</footer>

templates/partners/navbar.html
{% load static %}
<div class="navbar-bg"></div>
<nav class="navbar navbar-expand-lg main-navbar">
    <form class="form-inline mr-auto">
        <ul class="navbar-nav mr-3">
        <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
        <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a></li>
        </ul>
        <div class="search-element">
        
        
        </div>
    </form>
    <ul class="navbar-nav navbar-right"> 
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                <img alt="image" src="{{ request.user.partnerusers.profile_pic.url }}" class="rounded-circle mr-1">
                <div class="d-sm-none d-lg-inline-block">Hi, {{ request.user.first_name }} {{ request.user.last_name }}</div>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <div class="dropdown-title">Logged in 5 min ago</div>

                <a href="{% url 'partners:partner_account_update_view' %}" class="dropdown-item has-icon">
                    <i class="fas fa-user"></i> Your Profile
                </a>

                <a href="features-activities.html" class="dropdown-item has-icon">
                    <i class="fas fa-bolt"></i> Your Activities
                </a>

                <a href="features-settings.html" class="dropdown-item has-icon">
                    <i class="fas fa-cog"></i> Your Calendar
                </a>

                <div class="dropdown-divider"></div>

                <a href="features-settings.html" class="dropdown-item has-icon">
                    <i class="fas fa-cog"></i> Settings
                </a>

                <div class="dropdown-divider"></div>

                <a href="{% url 'logout_view' %}" class="dropdown-item has-icon text-danger">
                    <i class="fas fa-sign-out-alt"></i> Logout
                </a>
            </div>
        </li>
    </ul>
</nav>

templates/partners/sidebar.html
{% load static %}

{% url 'partners:partner_account_update_view' as partner_account_update %}

<div class="main-sidebar sidebar-style-2">
    <aside id="sidebar-wrapper">
        <div class="sidebar-brand mt-2">
            <img src="{% static 'crm/img/logo.png' %}" alt="logo" width="100" class="">
        </div>
        <div class="sidebar-brand sidebar-brand-sm">
            <a href="index.html">CPRx</a>
        </div>
        
        <ul class="sidebar-menu" style="margin-top: 100px;">
            <li class="menu-header">Main Menu</li>

            <li class="dropdown">
                <a href="{% url 'partners:partner_dashboard_view' %}" class="nav-link"><i class="fas fa-tachometer-alt"></i></i><span>Dashboard</span></a>
            </li>
            <li class="dropdown">
                <a href="{% url 'jobs:jobs_view' %}" class="nav-link"><i class="fas fa-list-ul"></i><span>Jobs</span></a>
            </li>
            <li class="dropdown">
                <a href="{% url 'partners:partner_account_update_view' %}" class="nav-link"><i class="fas fa-user"></i><span>Profile</span></a>
            </li>
            <li class="dropdown">
                <a href="{% url 'partners:partner_resume_panel_view' %}" class="nav-link"><i class="fas fa-address-book"></i><span>Resume</span></a>
            </li>
            <li class="dropdown">
                <a href="{% url 'partners:partner_media_upload_view' %}" class="nav-link"><i class="fas fa-folder-plus"></i><span>Documents</span></a>
            </li>
            <li class="dropdown">
                <a href="#" class="nav-link"><i class="far fa-calendar-alt"></i><span>Calendar</span></a>
            </li>
            <li class="dropdown">
                <a href="#" class="nav-link"><i class="fas fa-envelope"></i><span>Messages</span></a>
            </li>
            <li class="dropdown">
                <a href="#" class="nav-link"><i class="fas fa-wallet"></i><span>Wallet</span></a>
            </li>

        </ul>

        <ul class="sidebar-menu">
            <li class="menu-header">Settings</li>

            <li class="dropdown">
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-fingerprint"></i><span>Security</span></a>
                <ul class="dropdown-menu">
                    <li class=''><a class="nav-link" href="">Account</a></li>
                    <li class=''><a class="nav-link" href="">Notifications</a></li>
                </ul>
            </li>
        </ul>



        <div class="mt-4 mb-4 p-3 hide-sidebar-mini">
            <a href="{% url 'logout_view' %}" class="btn btn-primary btn-lg btn-block btn-icon-split">
            <i class="fas fa-sign-out-alt"></i> LOGOUT
            </a>
        </div>   
    </aside>
</div>